import { test, expect } from '@playwright/test'

test('estimates and weekly budget can be created, edited and reloaded', async ({ page }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-09T12:00:00'))
  await page.addInitScript(() => {
    if (localStorage.getItem('oliarev-study-planner-v2')) return
    localStorage.setItem('oliarev-study-planner-v2', JSON.stringify({
      subjects: [{ id: 's', name: 'Avtalerett', short: 'Avtalerett' }], lectures: [],
    }))
  })
  await page.goto('/')
  await page.getByRole('button', { name: 'Nytt arbeidskrav', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Nytt arbeidskrav' })
  await dialog.getByLabel('Tittel').fill('Drøft avtalen')
  await dialog.getByLabel('Frist', { exact: true }).fill('11/09/2026')
  await dialog.getByRole('spinbutton', { name: /Estimert tid/ }).fill('10081')
  await dialog.getByRole('button', { name: 'Legg til arbeidskrav' }).click()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('spinbutton', { name: /Estimert tid/ }).fill('90')
  await dialog.getByRole('button', { name: 'Legg til arbeidskrav' }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Arbeidskrav', exact: true }).click()
  await page.getByRole('button', { name: 'Rediger arbeidskrav' }).click()
  dialog = page.getByRole('dialog', { name: 'Rediger arbeidskrav' })
  await expect(dialog.getByRole('spinbutton', { name: /Estimert tid/ })).toHaveValue('90')
  await dialog.getByRole('spinbutton', { name: /Estimert tid/ }).fill('120')
  await dialog.getByRole('button', { name: 'Lagre endringer' }).click()

  await page.getByRole('button', { name: 'Nytt pensum', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Nytt pensum' })
  await dialog.getByLabel('Pensum', { exact: true }).fill('Avtaleinngåelse')
  await dialog.getByRole('spinbutton', { name: /Estimert tid/ }).fill('60')
  await dialog.getByRole('button', { name: 'Uke', exact: true }).click()
  await dialog.getByRole('option', { name: /Uke 37/ }).click()
  await dialog.getByRole('button', { name: 'Legg til pensum' }).click()
  await page.getByRole('button', { name: 'Pensum', exact: true }).click()
  await page.getByRole('button', { name: 'Rediger pensum' }).click()
  dialog = page.getByRole('dialog', { name: 'Rediger pensum' })
  await expect(dialog.getByRole('spinbutton', { name: /Estimert tid/ })).toHaveValue('60')
  await dialog.getByRole('spinbutton', { name: /Estimert tid/ }).fill('30')
  await dialog.getByRole('button', { name: 'Lagre endringer' }).click()

  await page.getByRole('button', { name: 'Oversikt', exact: true }).click()
  const workload = page.getByRole('region', { name: 'Ukebelastning' })
  const budget = workload.getByRole('spinbutton', { name: 'Ukentlig selvstudiebudsjett (minutter)' })
  await expect(workload).toContainText('150 min estimert for ufullførte oppgaver')
  await budget.fill('180')
  await expect(workload).toContainText('Sett et budsjett')
  await workload.getByRole('button', { name: 'Lagre ukebudsjett' }).click()
  await expect(workload).toContainText('30 min tilgjengelig i budsjettet')
  await workload.screenshot({ path: testInfo.outputPath('workload-desktop.png'), animations: 'disabled' })
  await workload.getByRole('button', { name: 'Neste uke', exact: true }).click()
  await expect(workload).toContainText('Ingen ufullførte oppgaver i valgt uke.')
  await workload.getByRole('button', { name: 'Forrige uke', exact: true }).click()
  await expect(workload).toContainText('150 min estimert')

  await page.reload()
  await page.getByRole('button', { name: 'Oversikt', exact: true }).click()
  await expect(budget).toHaveValue('180')
  await expect(workload).toContainText('150 min estimert')
  await budget.fill('0')
  await workload.getByRole('button', { name: 'Lagre ukebudsjett' }).click()
  await expect(workload).toContainText('150 min over budsjettet')
  await budget.fill('')
  await workload.getByRole('button', { name: 'Lagre ukebudsjett' }).click()
  await expect(workload).toContainText('Sett et budsjett')
  await page.setViewportSize({ width: 375, height: 812 })
  await workload.screenshot({ path: testInfo.outputPath('workload-mobile.png'), animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)).toBe(false)
})
